version: 2

sources:
  - name: staging
    database: "{{ env_var('DBT_DATABASE', 'customer-segmentation-123') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'ecommerce_customer_data') }}"

    tables:
      - name: order_items
      - name: products
      - name: users
   
models:
  - name: stg_order_items
    description: >
      The `order_items` table contains information about individual items in customer orders.
      Each row represents a specific item in an order, which may consist of multiple products.
      The `order_item_id` is used to uniquely identify each item, while `order_id` links the item to a specific order. 
      The data is cast to the appropriate types for further analysis, ensuring consistency and accuracy in the final reporting.

    columns:
      - name: order_item_id
        description: Unique identifier for each order item.
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: order_id
        description: Identifier for the order that the item belongs to.
        tests:
          - not_null:
              severity: warn
      - name: user_id
        description: Identifier for the user who placed the order.
      - name: product_id
        description: Identifier for the product in the order item.
      - name: order_time
        description: The timestamp when the order item was placed.
      - name: sale_price
        description: The sale price of the product in the order item.

  - name: stg_products
    description: >
      The `products` table contains detailed information about each product available for sale. 
      Each row represents a unique product, providing details such as cost, category, name, brand, 
      sale price, and the department to which it belongs. The data is cast to the appropriate types 
      for further analysis, ensuring consistency and accuracy in the final reporting.

    columns:
      - name: product_id
        description: Unique identifier for each product.
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: cost
        description: The cost of the product.
      - name: category
        description: The category to which the product belongs.
      - name: product_name
        description: The name of the product.
      - name: product_brand
        description: The brand of the product.
      - name: sale_price
        description: The retail price of the product.
      - name: department
        description: The department where the product is categorized (e.g., Men's, Women's).

  - name: stg_users
    description: >
      The `users` table contains information about the customers using the platform. 
      Each row represents an individual user with details such as their ID, name, email, 
      age, gender, location (city and country), and traffic source. The data is cast to the appropriate types 
      for further analysis, ensuring consistency and accuracy in the final reporting.

    columns:
      - name: user_id
        description: Unique identifier for each user.
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: first_name
        description: The first name of the user.
      - name: last_name
        description: The last name of the user.
      - name: email
        description: The email address of the user.
      - name: age
        description: The age of the user.
      - name: gender
        description: The gender of the user. Possible values are 'Female', 'Male', or 'unknown'.
      - name: city
        description: The city where the user resides.
      - name: country
        description: The country where the user resides.
      - name: traffic_source
        description: The source of traffic that brought the user to the platform.
      - name: registration_date
        description: The date and time when the user registered on the platform.
      - name: user_geom
        description: The geographical location of the user.