services:
  kestra:
    image: kestra/kestra:latest
    command: server local
    ports:
      - "8080:8080"
    volumes:
      - kestra-data:/app/storage
    networks:
      - kestra_default
    user: root

volumes:
  kestra-data:

networks:
  kestra_default:
    driver: bridge