services:
  kestra:
    image: kestra/kestra:latest
    command: server local
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - kestra-data:/app/storage
    user: root
    
volumes:
  kestra-data:
