services:
  kestra:
    image: kestra/kestra:latest
    container_name: kestra-server
    ports:
      - "8080:8080"
    volumes:
      - kestra-data:/app/storage
    environment:
      - KESTRA_STORAGE_TYPE=local
    command: server local

volumes:
  kestra-data: